# Write your MySQL query statement below
SELECT S.USER_ID, 
IFNULL(ROUND (SUM(ACTION ='CONFIRMED')/COUNT(*),2),0.0) AS
CONFIRMATION_RATE
FROM SIGNUPS S
LEFT JOIN CONFIRMATIONS C
ON S.USER_ID=C.USER_ID
GROUP BY S.USER_ID