# Write your MySQL query statement below

SELECT A1.MACHINE_ID,ROUND(AVG(A2.TIMESTAMP-A1.TIMESTAMP),3)
AS PROCESSING_TIME
FROM ACTIVITY A1
INNER JOIN ACTIVITY A2
ON A1.PROCESS_ID=A2.PROCESS_ID
AND A1.MACHINE_ID=A2.MACHINE_ID
AND A1.TIMESTAMP<A2.TIMESTAMP
GROUP BY A1.MACHINE_ID;